server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:memDb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
    platform: h2
    hikari:
      connection-test-query: SELECT 1

  h2:
    console.enabled: true

  jpa:
    database: H2
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        I added it because multiline sql script didn't work but it wasn't necessary
#        hbm2ddl:
#          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        format_sql: false
    show-sql: true

  main:
    web-application-type: servlet

  flyway:
#    user, password, url are not necessary
#    user: sa
#    password:
#    url: jdbc:h2:mem:memDb
    baseline-on-migrate: true
    validate-on-migrate: true
