server:
  port: 8080

spring:
  datasource:
    url: ${databaseUrl}
    username: ${usernameDB}
    password: ${passwordDB}
    driverClassName: org.postgresql.Driver
    platform: postgres
    hikari:
      connection-test-query: SELECT 1

  h2:
    console.enabled: true

  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    show-sql: true

  main:
    web-application-type: servlet

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
